FROM python:alpine

WORKDIR /app

# Copy application files

COPY function/requirements.txt .

# Setup Python virtual environment & install deps
RUN python3 -m venv .docker_venv
RUN source .docker_venv/bin/activate
RUN pip3 install -r requirements.txt

# Add your cron job file to the container
ADD cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN crontab /etc/cron.d/cronjobs

COPY credentials.ini .
COPY route-config.ini .
COPY function/ .

# Start cron service
CMD ["crond", "-f"]
# CMD ["python3", "-u", "docker_compose_runtime.py"]