name: [Data Analyzer] Continuous Deployment to ECS

on:
  push:
    branches:
      - space-data-analyzer-mvp
env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: "data-analyzer-ecr-repo" # Amazon ECR repository name
  ECS_CLUSTER: sat-scan-cluster # Amazon ECS cluster name
  ECS_SERVICE: data-analyzer-service # Amazon ECS service name
  ECS_TASK_DEFINITION: ./infrastructure/task-definitions/aws/data-analyzer-container.json
  CONTAINER_NAME: data-analyzer-family # Name specified in containerDefinitions section of task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLIENT_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create credentials.ini
        env:
          SAT_SCAN_API_KEY: ${{ secrets.SAT_SCAN_API_KEY }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          cd applications/sat-scan-api

          cat <<EOF > credentials.ini
          [sat-scan-api]
          key=$SAT_SCAN_API_KEY
          EOF

          echo "Created .credentials.ini"

      - name: Download infrastructure configuration
        run: |
          rm applications/space-data-analyzer/route-config.ini
          aws s3 cp s3://sat-scan-route-config/route-config.ini applications/space-data-analyzer/route-config.ini
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_SECRET }}
          AWS_DEFAULT_REGION: "us-east-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build docker container and push it to ECR for ECS deploy
          cd applications/space-data-analyzer
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
