name: Data Collector - Continuous Deployment to Lambda

on:
  push:
    branches:
      - lambda-clouddwatch-trigger

env:
  AWS_REGION: "us-east-2"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLIENT_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLIENT_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create credentials.ini
        env:
          SPACE_TRACK_API_CLIENT: ${{ secrets.SPACE_TRACK_API_CLIENT }}
          SPACE_TRACK_API_SECRET: ${{ secrets.SPACE_TRACK_API_SECRET }}
        run: |
          cd applications/space-data-collector

          cat <<EOF > credentials.ini
          [space-track.org]
          username=$SPACE_TRACK_API_CLIENT
          password=$SPACE_TRACK_API_SECRET
          EOF

          echo "Created .credentials.ini"

      - name: Download infrastructure configuration
        run: |
          rm applications/space-data-collector/route-config.ini
          aws s3 cp s3://sat-scan-route-config/route-config.ini applications/space-data-collector/route-config.ini
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_SECRET }}
          AWS_DEFAULT_REGION: "us-east-2"

      - name: Package Data-Collector and Push to S3
        id: build-image
        run: |
          cd applications/space-data-collector

          # Install packages
          rm -rf package
          cd function
          pip install --target ../packages -r requirements.txt
          cd ..
          cp -r packages/* function

          # Copy configuration files
          cp route-config.ini function
          cp credentials.ini function
          cp space_track_requests.yml function

          # Zip & upload build artifact to S3
          cd function
          zip -r lambda_code.zip .
          aws s3 cp lambda_code.zip s3://sat-scan-data-collector

      - name: Deploy Lambda
        id: deploy-image
        run: |
          aws lambda update-function-code \
            --function-name  data_collector_lambda \
            --s3-bucket sat-scan-data-collector --s3-key lambda_code.zip
