name: Test - Unit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment
        run: |
          python3 -m pip install --upgrade pip
          # sudo apt update
          # sudo apt install nodejs
          # sudo apt install npm
          # npm install --global yarn

      - name: Run Data Analyzer Tests
        run: |
          cd applications/space-data-analyzer
          pip3 install -r requirements.txt
          make unit

      - name: Run Data Collector Tests
        run: |
          cd applications/space-data-collector
          pip3 install -r requirements.txt
          make unit

      - name: Run Sat Scan API Tests
        run: |
          cd applications/sat-scan-api
          pip3 install -r requirements.txt
          make unit

      - name: Run Sat Scan Web Tests
        run: |
          cd applications/sat-scan-web
          yarn
          yarn test
